apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "colacao.fullname" . }}-votacion
  labels:
    {{- include "colacao.labels" . | nindent 4 }}
    app: colacao-app
    concern: app-votacion
spec:
  replicas: {{ .Values.deploy.votacion.replicaCount }}
  selector:
    matchLabels:
      {{- include "colacao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "colacao.selectorLabels" . | nindent 8 }}
        app: colacao-app
        concern: app-votacion
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "colacao.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-votacion
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deploy.votacion.image }}:{{ .Values.deploy.votacion.imageTag }}"
          imagePullPolicy: {{ .Values.deploy.votacion.pullPolicy }}
          command: ["python"]
          args: ["app.py"]
          ports:
            - name: votacion
              containerPort: {{ .Values.deploy.votacion.port }}
              protocol: TCP
            - name: votacionpriv
              containerPort: {{ .Values.deploy.votacion.portPriv }}
              protocol: TCP

