apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "colacao.fullname" . }}-resultados
  labels:
    {{- include "colacao.labels" . | nindent 4 }}
    app: colacao-app
spec:
  replicas: {{ .Values.deploy.resultados.replicaCount }}
  selector:
    matchLabels:
      {{- include "colacao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "colacao.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "colacao.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-resultados
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deploy.resultados.image }}:{{ .Values.deploy.resultados.imageTag }}"
          imagePullPolicy: {{ .Values.deploy.resultados.pullPolicy }}
          command: ["nodemon"]
          args: ["server.js"]
          
          ports:
            - name: resultados
              containerPort: {{ .Values.deploy.resultados.port }}
              protocol: TCP
