apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "colacao.labels" . | nindent 4 }}
    app: colacao-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deploy.redis.port }}
      targetPort: {{ .Values.deploy.redis.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "colacao.selectorLabels" . | nindent 4 }}
