apiVersion: v1
kind: Service
metadata:
  name: resultados
  labels:
    {{- include "colacao.labels" . | nindent 4 }}
    app: colacao-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deploy.resultados.port }}
      targetPort: {{ .Values.deploy.resultados.port }}
      protocol: TCP
      name: resultados
  selector:
    name: {{ include "colacao.fullname" . }}-resultados
